// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrOCasJLVcZ4WbQX2nOiUo9PZQCxYoAEU',
    appId: '1:652618372904:web:3cc8f60caefa3a9672e21d',
    messagingSenderId: '652618372904',
    projectId: 'magic-companion-rag',
    authDomain: 'magic-companion-rag.firebaseapp.com',
    databaseURL: 'https://magic-companion-rag-default-rtdb.firebaseio.com',
    storageBucket: 'magic-companion-rag.firebasestorage.app',
    measurementId: 'G-72H8J5SF3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-aSFvjLaAkqW0prTQt19368Qhkmoh4nE',
    appId: '1:652618372904:android:c746e4a151ec7df072e21d',
    messagingSenderId: '652618372904',
    projectId: 'magic-companion-rag',
    databaseURL: 'https://magic-companion-rag-default-rtdb.firebaseio.com',
    storageBucket: 'magic-companion-rag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp5zJLTN6EydHfB6YVEEJPQg6ezz6teEc',
    appId: '1:652618372904:ios:eb7fe6054766030472e21d',
    messagingSenderId: '652618372904',
    projectId: 'magic-companion-rag',
    databaseURL: 'https://magic-companion-rag-default-rtdb.firebaseio.com',
    storageBucket: 'magic-companion-rag.firebasestorage.app',
    iosBundleId: 'com.example.magicCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp5zJLTN6EydHfB6YVEEJPQg6ezz6teEc',
    appId: '1:652618372904:ios:eb7fe6054766030472e21d',
    messagingSenderId: '652618372904',
    projectId: 'magic-companion-rag',
    databaseURL: 'https://magic-companion-rag-default-rtdb.firebaseio.com',
    storageBucket: 'magic-companion-rag.firebasestorage.app',
    iosBundleId: 'com.example.magicCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrOCasJLVcZ4WbQX2nOiUo9PZQCxYoAEU',
    appId: '1:652618372904:web:e14b3703f4d7575972e21d',
    messagingSenderId: '652618372904',
    projectId: 'magic-companion-rag',
    authDomain: 'magic-companion-rag.firebaseapp.com',
    databaseURL: 'https://magic-companion-rag-default-rtdb.firebaseio.com',
    storageBucket: 'magic-companion-rag.firebasestorage.app',
    measurementId: 'G-RYNPN4G627',
  );
}
